### ISSUE TITLE
Problem with background audio

### ISSUE THREAD

**Issue by burakyuksek** [munawarb/Three-D-Velocity#104]
When I leave the window, looping music like pausing music decrease in volume. When I come back, it stops.

**Comment by munawarb** [comment]
Hi,
If you press F7 to turn up the volume when it stops, does the music unmute?

**Comment by burakyuksek** [comment]
Hello,
The background and menu music volumes up properly. The pause music is problematic.

**Comment by munawarb** [comment]
Ok. I'd like you to test one thing though. You wrote that the music stops. When it stops and you press f7, does it come back? Or does the music remain silent until you go back to the main menu?

**Comment by burakyuksek** [comment]
Hello,
No, when I press f7 it doesn't come back. However when I unpause and pause the game again it comes back.

**Comment by munawarb** [comment]
The pause music is no longer set at half volume since this was causing all music volume to become quieted by one-half. I think this is what was causing your problem.
