### ISSUE TITLE
Issue with bullets

### ISSUE THREAD

**Issue by burakyuksek** [munawarb/Three-D-Velocity#114]
Hello,
Once I try to shoot exceeding the vertical range of the bullets, no matter how low I get to the ground before trying again, they just don't work, they miss all the time, how close doesn't matter.

**Comment by munawarb** [comment]
Hi @burakyuksek,
I don't quite understand what you mean here. Can you reexplain in more detail or give steps to reproduce the problem?

**Comment by burakyuksek** [comment]
hello,
1. Lock on a target such as the airbase. Don't be in range yet
2. Begin raising nose so you get higher. Get up to like 20000 feat
3. Fire when in range. you will see that nothing will happen
4. Once you get passsed the airbase, flip the jet and get down.
5. Fire from the other side. Nothing will happen
