### ISSUE TITLE
Problems with private games

### ISSUE THREAD

**Issue by sanslash332** [munawarb/Three-D-Velocity#13]
Hello munawar,
The game crash when someone joins a private game. I don't know where is the log saved, but with a friend can reproduse this situation every time.

Player a create a private deathmatch game
player b joins to that game 
player b gets a crash error and the game closes
player a gets a notification of that player b is unexpectedly desconnected from server
The game for player a continues open, but don't respond so you must press alt+f4 to close it.

We can't test the team deathmatch game, but the free for all works fine.

thanks :3

**Comment by munawarb** [comment]
Hi,
Thanks for the detailed steps to reproduce this.

**Comment by sanslash332** [comment]
Your welkome. I would post the log as  spected in this situation, but I loose it :P 

 

Thanks for fix the problem :P
