### ISSUE TITLE
CQC sound panning is slightly buggy

### ISSUE THREAD

**Issue by blindninja97** [munawarb/Three-D-Velocity#14]
currently, if you transition from normal gameplay to ground combat with a course that isn't 0, the stereo field of the fight pans to reflect your flight heading
example, if you begin the fight when you were originally flying at 270 degrees, sounds pan from right to left when you move forward and backwards

**Comment by munawarb** [comment]
Thanks for the detailed information; this is helpful in troubleshooting the problem :)
