### ISSUE TITLE
 Question about code. 

### ISSUE THREAD

**Issue by MichaelPyron** [munawarb/Three-D-Velocity#21]
Hi,  I am new to this. The question is, can I just paste files into the folder, or how do I add the code? I know nothing about this. Thanks for your help. I want to get the new updates.

**Comment by munawarb** [comment]
Hi @MichaelPyron,
That's a good question. You can check the change log from time to time. If there's no new version listed, the binaries haven't been updated. The commits you're seeing me make are just notifications you're getting as I work on things, but those changes haven't necessarily made into the binaries yet; they're just available in the source version. The binaries are always the latest version listed in the change log.

From time to time I'll fix enough things and call it a new release, and update the binaries to incorporate the changes, but until that happens the only way to get the new features is to compile the source code.
