### ISSUE TITLE
Game freezing, trottle and afterburners

### ISSUE THREAD

**Issue by GaPx00** [munawarb/Three-D-Velocity#31]
First let Me thank You for creating this Game and making it Open Source. The Game is very adictive and realistic and I Am happy to be able to play the full game instead of just the demo.
I'm playing it on a PC running Windows 10 Pro 64 Bit and Am using a T.otas PS3 Flightstick and the problems I'm having with the game are:
1. Every Time I load the Game I get a error message saying there was a error mapping the keys or they have been mapped with a older Game version which makes Me having to assign keys to the Flight Stick every time I want to play.
2. If I select a type of Game, lets say for example Racing Mode I can play it for a while and sometimes the game just freezes, sounds keep playing but i cannot do anything with the controls, either using the Flight Stick or the keyboard and have to close the game.
3. If I select a type of Game and after playing it for a while I want to change to a different type of Game and click on start a new game it will always play whatever I was playing first, for example Training Mode...
4. I cannot trottle down or deactivate the Afterburners... I can trottle up using the flightstick but it always goes into full trottle and automatically activates the afterburners and I can of course just activate the afterburners by pressing the corresponding key.
But when I want to slow down the Plane and use the Flight Stick to trottle down it works as long as I'm twisting the rudder but as soon as i release it Airspeed goes up again and the afterburners kick-in making it impossible to manage fuel and of course slowing down the Plane for landing...

**Comment by munawarb** [comment]
Hi @GaPx00,
I'm so glad you enjoy Three-D Velocity!
1. Try to delete your old keymap file, or go into settings -> map keys -> restore to default. This will reset your keymap file and the error will go away.

4. This is quite interesting. When you push down on the throttle stick to slow the plane down, do the afterburners turn off? Twisting the rudder control should not slow your plane down at all. It sounds like the stick is mapped incorrectly somehow. Are you using Windows native drivers, or did you install drivers from the manufacturer?

**Comment by munawarb** [comment]
1 and 3 are expected behaviors; 4 might be an issue with the particular joystick, but this will require more information. I can't reproduce it on the flight stick I have. Point 2 is not reproducible. Feel free to re-open if these issues persist.
