### ISSUE TITLE
Problem with bots in multiplayer

### ISSUE THREAD

**Issue by burakyuksek** [munawarb/Three-D-Velocity#37]
When a bot kills you then you join back in free for all, the bot gets stuck in the ground and does nothing. You have to kick it.

**Comment by munawarb** [comment]
Hi @burakyuksek, I'm not able to reproduce this and I tried multiple times. Are you running the latest version of the game?

I spun up a local server and added several bots. I waited for them to kill each other off and when a few were remaining I exited and rejoined. It worked fine.

**Comment by munawarb** [comment]
Closing because I can't reproduce this one and there was no follow-up for some time.
