### ISSUE TITLE
game freezes after a loss when playing on the server and a restart of the game is required

### ISSUE THREAD

**Issue by nickgaw** [munawarb/Three-D-Velocity#42]
When I play as a pilot and lose and then try to play the free for all game again I am unable to get off of the ground and I have to restart the game.  All bots I had created before are cleared so I don't get to fight them.

**Comment by munawarb** [comment]
Hi @nickgaw, can you download version 2.17 and check to see if this problem is resolved? I've made changes in 0484af4  that might fix this issue. Thanks!

**Comment by nickgaw** [comment]
I also have noticed that if there is no chat rooms created and you try to join one the game also freezes and also have noticed that after around 6 times of playing and creating bots you are no longer able to create any new bots the game is still playable but no new bots can be created.
