### ISSUE TITLE
fuel when starting out is only 26000 pounds not 36000 pounds like after a refuel

### ISSUE THREAD

**Issue by nickgaw** [munawarb/Three-D-Velocity#44]
I think that regardless of what mode you are in and how you launch the fuel should be at the maximum 36000 pounds rather then 26000 pounds like it is as you first launch so you get the entire fuel usage before you have to refuel.

**Comment by munawarb** [comment]
Hi @nickgaw, this is by design. Fighter jets launch with a smaller fuel payload to allow themselves to get airborne quicker, so this has been simulated in TDV.
