### ISSUE TITLE
Migrate library uses to NuGet

### ISSUE THREAD

**Issue by francipvb** [munawarb/Three-D-Velocity#45]
Hi,

I was exploring the repository and saw that the binary libs are versioned with the code.

Can you migrate your libs to nuget and use NuGet packages in place of hardcoded reference files?

I think that the majority of the libs are already posted on NuGet repository, the only lib that is unlikely to be there is the BPCSharedComponent.

Cheers,

**Comment by munawarb** [comment]
Hi @francipvb,
Thanks for the suggestion; I'll certainly look at it!

You're correct about `BPCSharedComponent.dll`, since this is a custom library I wrote.

**Comment by blindpilot** [comment]
Hey Munawar. 
I down loaded the 
Three-D-Velocity-Binaries-master.zip
Now when I go to install the program I receive the following error:
Error 1 can not open output file access is denied.
Now yes I went to tried to extract the files into the 
c:\program files (x86)\BPC Programs\3 D Velocity folder.
So why can’t I get the files to extract to that folder?
Many thanks. 
Ron

**Comment by munawarb** [comment]
This message is off topic for this issue; please don't treat GitHub as a mailing list. Posting off topic replies in a closed issue is against good GitHub etiquette.
 Open a new issue if you have a question. Thanks.
