### ISSUE TITLE
documentation for modifying the aircraft and enemies and weapons

### ISSUE THREAD

**Issue by nickgaw** [munawarb/Three-D-Velocity#46]
I would like to see some documentation added as to how to modify the aircraft and the enemies as well as the weapons like if you wanted to increase the range or set an enemy fighter to mainly use one weapon over another one.

**Comment by munawarb** [comment]
Hi @nickgaw,
I don't have plans to include full-fledged developer documentation with the source code. There are some doc comments scattered throughout the project and you can use a generator to give you the documentation in an easy-to-consume fashion, though the Microsoft tools to generate this documentation are limited and mostly commercial from what I remember.

If you want to set a weapon's range, you can use the `setRange` method that's called during a weapon's constructor. I hope this helps point you in the right direction!
