### ISSUE TITLE
having the ability to go to an altitude on autopilot

### ISSUE THREAD

**Issue by nickgaw** [munawarb/Three-D-Velocity#47]
I would like to see a new feature added to the autopilot that allows you to enter an altitude that you wish to go to and then the aircraft would level out at that altitude when reached as this would help in landing or in making sure you don't climb to high.

**Comment by munawarb** [comment]
I don't see a way to do this without getting one of the original voice actors to voice the prompt. Closing until there exists a time when the resource becomes available.
