### ISSUE TITLE
TDV and WINE

### ISSUE THREAD

**Issue by celtichawk** [munawarb/Three-D-Velocity#50]
I've been trying to get TDV to work under WINEWINE. What exactly are the requirements for getting it to fire up on the latest WINE? Asie from, obviously, TDV and WINE, I'm guessing I need SAPI and .NET Framework, right?

**Comment by munawarb** [comment]
Hi @celtichawk,
Yes, you'll need .NET Framework 4.6 or higher. You will also need DirectX, along with the XAudio2 dependency. The executable to install required DirectX components is on the main page.

You'll also need SAPI but this is only for the multiplayer server.
