### ISSUE TITLE
Error during gameplay

### ISSUE THREAD

**Issue by caiohenriquerls** [munawarb/Three-D-Velocity#51]
Firstly, I'd like to apologise about before, I was still learning how to use the site properly.
My issue is the following: I'm able to pass the first missions of the mission mode easilly.
But when it comes to the power plant part, the game simply closes, the system says an eror ocurred. Therefore, I'm unable to continue.

**Comment by munawarb** [comment]
@caiohenriquerls No problem and thanks for reposting!

Can you provide your error log?
`%appdata%\BPCPrograms\tdv2\errorXXX.log`

**Comment by nickgaw** [comment]
I also get this issue and also get an error when trying to load a saved game from the last version.  I will attach the error log so you can see it.
[errorSep-1-2018 10-31-25 PM-0.log](https://github.com/munawarb/Three-D-Velocity/files/2344423/errorSep-1-2018.10-31-25.PM-0.log)

**Comment by caiohenriquerls** [comment]
Hello,

I’m pasting the contentes of the file here. Some parts of it are in Portuguese, if you need my help to translate, let me know.

Error log, created with build version 2.18.0.34585: 

Error base exception: System.OverflowException: Operação aritmética resultou em um estouro.

   em TDV.Weapons.getWeight() na C:\Users\munawar\projects\Three-D-Velocity\TDV\Weapons.cs:linha 917

   em TDV.Aircraft.getWeight() na C:\Users\munawar\projects\Three-D-Velocity\TDV\Aircraft.cs:linha 4689

   em TDV.Projector.getTotalWeight() na C:\Users\munawar\projects\Three-D-Velocity\TDV\Projector.cs:linha 968

   em TDV.Projector.getWeightRatio() na C:\Users\munawar\projects\Three-D-Velocity\TDV\Projector.cs:linha 1034

   em TDV.Projector.move() na C:\Users\munawar\projects\Three-D-Velocity\TDV\Projector.cs:linha 352

   em TDV.Aircraft.move() na C:\Users\munawar\projects\Three-D-Velocity\TDV\Aircraft.cs:linha 701

   em TDV.Holder.activate() na C:\Users\munawar\projects\Three-D-Velocity\TDV\Holder.cs:linha 112

Error Description: Operação aritmética resultou em um estouro.

Stack trace:    em TDV.Weapons.getWeight() na C:\Users\munawar\projects\Three-D-Velocity\TDV\Weapons.cs:linha 917

   em TDV.Aircraft.getWeight() na C:\Users\munawar\projects\Three-D-Velocity\TDV\Aircraft.cs:linha 4689

   em TDV.Projector.getTotalWeight() na C:\Users\munawar\projects\Three-D-Velocity\TDV\Projector.cs:linha 968

   em TDV.Projector.getWeightRatio() na C:\Users\munawar\projects\Three-D-Velocity\TDV\Projector.cs:linha 1034

   em TDV.Projector.move() na C:\Users\munawar\projects\Three-D-Velocity\TDV\Projector.cs:linha 352

   em TDV.Aircraft.move() na C:\Users\munawar\projects\Three-D-Velocity\TDV\Aircraft.cs:linha 701

   em TDV.Holder.activate() na C:\Users\munawar\projects\Three-D-Velocity\TDV\Holder.cs:linha 112

De: Munawar Bijani [mailto:notifications@github.com] 
Enviada em: domingo, 2 de setembro de 2018 19:34
Para: munawarb/Three-D-Velocity
Cc: caiohenriquerls; Mention
Assunto: Re: [munawarb/Three-D-Velocity] Error during gameplay (#51)

 

@caiohenriquerls <https://github.com/caiohenriquerls>  No problem and thanks for reposting!

Can you provide your error log?
%appdata%\BPCPrograms\tdv2\errorXXX.log

**Comment by ObjectInSpace** [comment]
I'm getting this crash also Win10X64.

**Comment by munawarb** [comment]
Thanks for confirming. I'll look into it soon.

**Comment by caiohenriquerls** [comment]
Thanks!

 

De: Munawar Bijani [mailto:notifications@github.com] 
Enviada em: quinta-feira, 8 de novembro de 2018 20:11
Para: munawarb/Three-D-Velocity
Cc: caiohenriquerls; Mention
Assunto: Re: [munawarb/Three-D-Velocity] Error during gameplay (#51)

 

Thanks for confirming. I'll look into it soon.
