### ISSUE TITLE
Problem upon first launching TDV

### ISSUE THREAD

**Issue by BlazinWings** [munawarb/Three-D-Velocity#54]
Hi there,
I'm so glad to see that you are still developing this project! A friend of mine has recently gotten into TDV2, but is unable to start the program. he is running windows 7 64, and has downloaded the binary release, but every time he launches the game he receives the following error notification.
Error log, created with build version 2.18.0.34585: 
Error base exception: System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
   at TDV.SapiSpeech.disableJAWSHook()
   at TDV.GUI.startGame(Boolean firstTimeLoad) in C:\Users\munawar\projects\Three-D-Velocity\TDV\GUI.cs:line 261
Error Description: Method not found: '!!0[] System.Array.Empty()'.
Stack trace:    at TDV.SapiSpeech.disableJAWSHook()
   at TDV.GUI.startGame(Boolean firstTimeLoad) in C:\Users\munawar\projects\Three-D-Velocity\TDV\GUI.cs:line 261

I have tried sending him a settings.tdv file with the options configured to use SAPI as default, but this did not resolve the issue. He has no conflicting application data, and has since removed the settings file we tested with.
Help would be greatly appreciated.

**Comment by munawarb** [comment]
It looks like it's something to do with the library not using the updated version of .NET. Thanks for reporting it.
