### ISSUE TITLE
Landing beacon does not appear in list of targetable objects

### ISSUE THREAD

**Issue by ObjectInSpace** [munawarb/Three-D-Velocity#55]
In racing/deathmatch mode, if you are asked to land your plane, the beacon does not appear in the list of lockable objects. If you press L and break your lock, you are unable to reestablish the location of the landing zone and thus cannot land.

**Comment by munawarb** [comment]
Ok. I think a solution here is to disallow you to break the lock if you're locked onto the landing beacon.
