### ISSUE TITLE
Mislabeled fighters in mission mode

### ISSUE THREAD

**Issue by BlazinWings** [munawarb/Three-D-Velocity#56]
First of all, thanks so much for your commitment! The new release fixed the bug I was just about to report, and I'm so glad to see that this game is still being revised.
 I'm not sure if this is the case in all situations, and I believe I've seen this issue come up somewhere else, but after destroying the airbase, the two fighters that take off are both labeled as fighter 1. I see in a previous thread that the game randomly labels fighters based on their sound description, or at least, that's how I understood your response. However, since I have not seen any instance in which there are more than six fighters on a map, would it be possible to insert a check in which the game does not select more than one fighter per sound template?

**Comment by munawarb** [comment]
Hi @BlazinWings,
You're welcome! Glad you're enjoying the updates. Sure, I'll look into it. At least in the case of the Airbase, this change can probably be made. My concern is the many more fighters that can appear later on, where there can be more than six at one time depending on how quickly you get rid of them. In that case there will be multiple same-numbered aircraft.

**Comment by BlazinWings** [comment]
Thanks so much for your efforts! Would it be possible to label the
fighters sequentially regardless of their sound profile? For example,
two fighters could utilize the sounds for fighter 1, but they could be
labeled fighters 1 and 2 respectively.
Unless by sound profile you mean voice acting. It is likely, now that
I think about it, that the voice actor recorded "fighter 1," "fighter
2," etc as their own voice clips to sound more natural. I wonder if
Mike would be open to recording a couple of extra clips to alleviate
this issue? My concern with this is that duplicate fighters with the
same label could be really misleading for players. IN addition, it can
be frustrating when switching targets. Even though one can usually
determine which plane is which based on position, that isn't always
the case.

**Comment by munawarb** [comment]
@BlazinWings,
I like your idea of sequentially naming them just like they are in Death Match. The fighters will range from 1 to 6. Since you're probably toast if you get more than six fighters to spawn in Mission Mode, this should mitigate the duplication problem.

@ObjectInSpace Thanks for the offer. I'll let you know if I need anything recorded! I've lost touch with all the voice actors that worked on the project for a while now so if there's a feature or fix that requires new recordings, I run up against a wall.
