### ISSUE TITLE
CQC: Investigate use of Left CTRL Key for alternative Keyboard Layouts

### ISSUE THREAD

**Issue by elliott94** [munawarb/Three-D-Velocity#59]
Whilst using a keyboard without a left Alt key (either a MacBook or the Apple Keyboard being two examples of this), I've noticed that it's currently impossible to grab an aponent which puts the player at a severe disadvantage. Could we possibly look at either remapping the key (using either CTRL keys as an example), or seeing if we could get the game to recognise these presses if the key has manually been remapped (using SharpKeys or another remapping utility)?

**Comment by munawarb** [comment]
Hi @elliott94 ,Great suggestion. I'll look into adding it.
