### ISSUE TITLE
Cruise missiles are OP

### ISSUE THREAD

**Issue by ObjectInSpace** [munawarb/Three-D-Velocity#60]
Cruise missiles are the easiest weapon to get a lock with, and the hardest to avoid if one is fired at you. They also have a farther effective range than anything else; while sidewinders technically have more range, in practice they rarely hit anything farther than three miles away, whereas cruise missiles reliably hit stationary targets 10 or so miles out. Worst of all, they one-shot everything: ground targets, fighters, choppers, and even Dark Blaze. I can beat the boss in roughly thirty seconds by getting a lock with the LTS at about 4 miles, then firing three cruise missiles about once every second as I afterburn in the opposite direction. As entertaining as it is to watch games beat themselves, it's not very satisfying.

**Comment by munawarb** [comment]
Hi @ObjectInSpace , By the design, the first point you made re: lock, will stay in the game. I've been thinking of the other point re: they wipe out any object they hit. Perhaps the effective damage an object can take from a cruise missile needs to be lowered? What are your thoughts on this? I've never had anyone say that the cruise missiles are too powerful. :)

**Comment by BlazinWings** [comment]
It makes sense to me that they demolish most everything they hit,
because that's how cruise missiles work in the real world. However,
they seem to make the boss fight particularly easy, which takes away
the challenge.

**Comment by ObjectInSpace** [comment]
I was bringing up the ways in which they are superior to the other weapons to show the overall disparity between them and the others. I'm not particularly picky as to how they are nurfed, I just think they should be in some way. Lowering the damage seems reasonable to me. I'm fine with them retaining a higher damage output than regular missiles, but nothing should one-shot the boss :)

**Comment by munawarb** [comment]
I've lowered the damage the missile can do to the boss significantly. Everything else is unaffected.
