### ISSUE TITLE
Allow status announcements to be read by screenreader/SAPI TTS

### ISSUE THREAD

**Issue by ObjectInSpace** [munawarb/Three-D-Velocity#61]
The speech rate for my screenreader is set much faster than the rate at which the game's speech is played, which makes accessing information more efficient. This particularly matters in multiplayer, where the game doesn't pause while you read things. It would be great if I could have status announcements (AKA anything that can be accessed from HUD mode) go to the screenreader.

**Comment by munawarb** [comment]
Related to #85 and #82. Resolved.
