### ISSUE TITLE
Make the REO go away

### ISSUE THREAD

**Issue by ObjectInSpace** [munawarb/Three-D-Velocity#62]
Rather than helpful, I find the RIO to be disruptive, anxiety-inducing and have basically trained myself to ignore everything he says. Every comment he makes has some noise associated with it, making him redundant in almost every circumstance. The only two exceptions to this I can think of are the reminder to put in or take out the landing gear, and the confirmation of an LTS lock (which also has a sound in multiplayer) It's also distracting to me to hear him screaming about missiles coming every five seconds that I already know about and have little chance of hitting me (like being 10 miles from a guard tower firing endless sidewinders) I don't mind him in cutscenes, but I'd really love to make him shove off during gameplay.

**Comment by munawarb** [comment]
Hi @ObjectInSpace , do you have access to recording equipment? If so, can you record an option for this?

**Comment by ObjectInSpace** [comment]
Sure thing! Recorded multiple versions of the option depending on what you decide to call the setting. If you choose something else, I can record that instead. Here you go:
https://dl.dropbox.com/s/ohxwzcdia3ia9uk/REO.wav

**Comment by munawarb** [comment]
Hi @ObjectInSpace , Thanks! I'm looking for an options entry. I'll use the Chase voice to say on and off, so from you I just need something like "RIO announcements." As with the other options, when the player presses ENTER, the game will say on or off. So can you record the options entry for me? Sorry for the misunderstanding.

**Comment by ObjectInSpace** [comment]
Oh, that reminds me: does the game provide the audio filter that makes it sound like a radio or will it need to be added to the audio file itself? I can do that but it probably will not sound exactly like the other announcements. But it will be closer than none at all.

**Comment by burakyuksek** [comment]
I don't think the game provides the filter.

ObjectInSpace <notifications@github.com> şunları yazdı (3 Ara 2018 01:57):

**Comment by ObjectInSpace** [comment]
OK, hopefully this is close enough.
https://dl.dropbox.com/s/7eiaf6q7m8i23h6/REO.flac

**Comment by munawarb** [comment]
@ObjectInSpace thanks! This one is great.

@NunoNunowicz Thanks for your contribution. I'll keep it around if I need it.
