### ISSUE TITLE
Please implement an 'objective' key

### ISSUE THREAD

**Issue by ObjectInSpace** [munawarb/Three-D-Velocity#63]
I would find it extremely helpful to be able to query the game as to my current goal. In mission mode, I often forget what sector I need to be in, or what target I need to destroy, particularly after reloading a save game I haven't played in some time or if I inadvertently skip a cutscene. It might also be useful for racing or deathmatch mode to tell new players what they need to do to win, and multiplayer mode could give a summary of the connected players and their positions.

**Comment by munawarb** [comment]
Hi @ObjectInSpace , Thanks for this suggestion. It's a great idea.

**Comment by chri79s** [comment]
Hey at object in space how do I download 3D velocity to my windows laptop?
Can you please help?
