### ISSUE TITLE
Game remembers your heading after loading a save

### ISSUE THREAD

**Issue by ObjectInSpace** [munawarb/Three-D-Velocity#64]
If you load a save while playing, when you next change direction, the game will re-orient you to the direction you were facing when you loaded the save, rather than the direction you were facing when the save was made. I believe you also lose an LTS lock if you have one when you save and then reload the save after losing it.

**Comment by munawarb** [comment]
I fixed this somewhere down the line but I don't know when. I just tested it to make sure and it works properly.
