### ISSUE TITLE
How do I download the three d velocity game?

### ISSUE THREAD

**Issue by chri79s** [munawarb/Three-D-Velocity#68]
Hey guys I’m trying to download the whole three d velocity game on my laptop windows computer and all I get is a bunch of files!

**Comment by BlazinWings** [comment]
Hi there,
You need to extract the zip folder to a desirable location on your
computer and then run tdv.exe within the new directory. There is no
executable installer, you have to extract the zip archive.

**Comment by munawarb** [comment]
Hi @chri79s , Please go to https://github.com/munawarb/Three-D-Velocity and scroll down to the Download heading. Instructions for downloading TDV are there.

**Comment by chri79s** [comment]
e extracted the files to the downloads folder how to run tab.exe?

**Comment by chri79s** [comment]
I’ve extracted all the files to the downloads folder and when I do a
windowsR I type in the tab.exe and it doesn’t show up

**Comment by munawarb** [comment]
I'm sorry, I'm confused as to what you're trying to do. There's no mention of tag.exe anywhere on the TDV main page. Are you sure you haven't got this GitHub confused with another software?

**Comment by chri79s** [comment]
I’m trying to download three-d-velocity on my laptop I extracted all the
files but how do I make a directory and run tab.exe?

**Comment by munawarb** [comment]
Where are you getting tag.exe from? There is no tag.exe anywhere in the 
extracted folder. All you have to do is unzip the file and run tdv.exe.
