### ISSUE TITLE
Force feedback does not work on PXN2113 ThunderPro

### ISSUE THREAD

**Issue by tgeczy** [munawarb/Three-D-Velocity#76]
Issue type: problem / requiring confirmation
product version: 2.24
Windows version: windows 10 v1809 (build 17763)

I'm using a force-feedback capable controller, the PXN2113 Thunder PRO.  (https://www.amazon.com/Joystick-YF2009-Controller-Vibration-Feedback/dp/B07BMGJGPV?th=1)
In TopSpeed 3 I can get force feedback working beautifully. When the car idles, the joystick vibrates. Note that there are multiple types on that amazon page, but all of them use the same hardware with different bodies for the joystick. A steering wheel, for instance.
I would like to see if others have force feedback working. The controler does require a custom device driver when I first got it, to enable this force feedback support. Either it's not using the same standard for the API used to control vibration calls (The controler that is) or something is amiss in compatibility. If others can definitively say, "no force feedback for me either," at least we can isolate the issue. Otherwise I completely get that coding custom joystick support is not really a thing a developer fancies doing until 3 in the morning, either.

**Comment by munawarb** [comment]
Hi @tgeczy,
This is strange. TDV has had force feedback support for a very long time now so I don't know why it's not working for you. Granted, I haven't tested it myself for years so it's possible I broke something a long while ago. I'll check it out, but I don't have a force feedback device myself so can't make any guarantees.
