### ISSUE TITLE
Multiplayer improvements

### ISSUE THREAD

**Issue by slannon97** [munawarb/Three-D-Velocity#79]
Hello,

Please add racing mode to multiplayer. Currently, the only thing players can do is battle one another. There should also be a global command to check all the players currently connected to the server.

Is there a way to remove the default chat rooms? I can't find any obvious ways to do so. Also, what is the password for the admin chat room? It seems a bit silly that I'm the server admin and don't know the password to one of my own channels. This doesn't appear to be documented anywhere.

**Comment by munawarb** [comment]
There's no way to remove the default rooms, but I can certainly look into it. I don't remember the password but it should be easy enough to find in the source. I'll update here when I find it.

As far as Racing Mode in multiplayer, the game isn't designed for this right now and I don't know how well it'll work.

I've thought about a global command for a while now; the trick will be the get a global lock on the server. I'll keep it in mind for the next update.

**Comment by nickgaw** [comment]
The password is in the source and is adminsrule but think there should be a way in the server to change the passwords like editing a text file rather then recompiling the server but understand about the security of why they are built into the binary file.
