### ISSUE TITLE
Having problems installing the open source version of TDV.

### ISSUE THREAD

**Issue by blindpilot** [munawarb/Three-D-Velocity#8]
Hello, to you Munawar, from Ron Kolesar.
I have down loaded both the following compressed folders. 
tdv-compiled.7z
And also the 
tdv-master.zip
In the first folder I see two exe files. 
The TDV.EXE file and the tdv.vshost.exe
Neither exe file will install and or set up the open source version of TDV. 
Now, I can down load and I also can install the TDV ver 2.exe program with no issues. 
But it is only a demo and is not the open source version. 
Can you help me to either trip the demo after I install it once again to open source or help me to figure out why the normal complressed exe files will not work for me. 
I've even tried of course with the UAC turned off and I am running windows 10 anniversary. 
Many Thanks Munawar. 
Ron Kolesar. 
P.S. 
Can you recommend a two stick USB handheld device that will support the force feedback feature of TDV that also will work with the newer processors with win 10 anniversary? 
I know this was a issue for when we all jumped from the older 32 bit processor where the force feedback feature worked in until we all jumped to the 64 bit processor where we never could find a USB controller that would work with the TDV force feedback feature. 
Glad to see you once again. 
Ron who is grounded until we can figure out why I can not take advantage of the open source version of TDV.

**Comment by munawarb** [comment]
@blindpilot, the Ttdv.exe file doesn't install the game; it runs it straight away. Are you receiving any error messages when you click tdv.exe?

I haven't found any good force feedback controllers. The best flight controllers I know of are from Thrustmaster, but they don't have force feedback.

**Comment by blindpilot** [comment]
Hello back at you Munawar. 
When I go down the list of files in the 
tdv-compiled.7z
Folder. 
I do see the following sub folder 
Three-D-Velocity-compiled
Inside that sub folder I did see the following file with the following long string after it:
tdv.exe 262 144 88 426 2017-02-02-02-03 1702 A c50b4847
Now, if I attempt to tap my applications key, it will not allow me to run as administrator. 
If I simply just smack the enter key on the the file, it states that it is copying, but to where. 
I even had someone from the Ms disability hotline watch me and they couldn’t figure it out either. 
Now, is it because I’m running windows 10 anniversary? 
Or also, is it the smart screen feature of win 10 anniversary stopping me from launching the TDV.exe file to install the program? 
I would love to link up with you via jaws and or via team viewer so you can see what I’m trying to show you. 
You I would trust. 
Glad as always to hear from you. 
Hope all is well. 
Ron

**Comment by munawarb** [comment]
@blindpilot there's no reason you should have to download the *.7z file. 
Download the release zip file that is linked here: 
https://github.com/munawarb/Three-D-Velocity in the readme, and you'll 
be good to go.


Also, it sounds like you're not extracting the archive. You need to 
extract the archive before you run tdv.exe; you can't run it from the 
archive directly.

**Comment by blindpilot** [comment]
Ok Munawar. 
Tried the following link. 
https://github.com/munawarb/Three-D-Velocity
I still can not find the down load. 
Can you give me step by step instructions on how to extract the archive? 
That way I hopefully then will be able to install the TDV program and start enjoying it and stop bugging you. 
Thanks. 
Ron

From: Munawar Bijani 
Sent: Monday, February 6, 2017 05:12 AM
    To: munawarb/Three-D-Velocity 
Cc: b    lindpilot ; Mention 
Su    bject: Re: [munawarb/Three-D-Velocity] Having problems installing the open source version of TDV. (#8)

@blindpilot there's no reason you should have to download the *.7z file. 
Download the release zip file that is linked here: 
https://github.com/munawarb/Three-D-Velocity in the readme, and you'll 
be good to go.


Also, it sounds like you're not extracting the archive. You need to 
extract the archive before you run tdv.exe; you can't run it from the 
archive directly.

**Comment by munawarb** [comment]
@blindpilot There's a section on the homepage for this repository that will explain how to directly download the executable. I think you're grabbing the source code, which is not what you want.
