### ISSUE TITLE
Possibility for Screen Reader to Speak All Status Messages

### ISSUE THREAD

**Issue by ironcross32** [munawarb/Three-D-Velocity#82]
Currently, the voicing for status messages is very slow talking for what feels like a fast-paced game. It would be nice if the screen reader could speak these messages instead, perhaps using Tolk as a method of doing this. Of course, this would be optional, but would allow much quicker information gathering and thus, quicker decision making in the heat of the moment.

**Comment by munawarb** [comment]
Along the lines of #85.

**Comment by burakyuksek** [comment]
I understand that this is very hard, but if this and translation support can be made it would be very good.

**Comment by munawarb** [comment]
I've begun work on this in [the svOrScreenReader branch](../tree/svOrScreenReader).
