### ISSUE TITLE
0° Click

### ISSUE THREAD

**Issue by ironcross32** [munawarb/Three-D-Velocity#83]
Currently, the course announcement can't keep up if you are banking hard and turning, or barrel rolling. I offer an alternative method. A periodic looping click that when centered in the stereo field, indicates you are travelling along a 0 degree heading. The click could orbit the field, and perhaps have a slightly lower pitch when behind the player. The click's looping speed could also be dynamic, looping more frequently during hard maneuvers, to provide as accurate a picture of the plane's current course as possible.

**Comment by munawarb** [comment]
Hi @ironcross32,
I think having a constant click would get annoying rather quickly. How about if the click plays when you're changing your course?

Are you able to send me a wave file of the type of clicking sound you're talking about so I can implement this?
