### ISSUE TITLE
Proposal: That NVDA can read the entire text of the game to make translation to any language.

### ISSUE THREAD

**Issue by Karlos82** [munawarb/Three-D-Velocity#85]
Hello: I write to propose an idea, I do not know if it will be very complicated.
I am from Spain and I speak little English. I am using a translator, sorry for the mistakes.
all the sounds of the game and the voices are excellent. The problem is that I do not understand English well. I do not know if it would be possible for the game to be said by NVDA. If possible, there are add-ons for NVDA that automatically translate the text and could play a lot more people who do not play because they do not know the language very much.
The idea is that while the voice sounds in English, it could be configured for NVDA to read as well. Thus, the Spanish player, Portuguese, French, etc., would use for example the Translate plugin and would automatically translate the text.
I hope to have explained.
Thank you.

**Comment by munawarb** [comment]
Hi,
Thanks for the suggestion. Do you mean the status messages to be spoken by NVDA? It can certainly be done, but it will take a very long time and much work to adapt the game from self-voicing to either self-voicing or synthesized output, especially if we're talking about menus and everything else.

I can work on it little by little though, so I'll leave this issue open.
