### ISSUE TITLE
Wierd namings in lock list

### ISSUE THREAD

**Issue by burakyuksek** [munawarb/Three-D-Velocity#90]
Hello,
I have reloaded my game and there are several choppers and ark blaze around me. I am using screen reader as output, and here is how they show up:
c 4 o'clock, 0.9 miles closure. wing on, 
c 4 o'clock, 0.9 miles closure. wing on, 
c 3 o'clock, 1.7 miles closure. Nose on, 
c 4 o'clock, 2.5 miles closure. wing on, 
db 7 o'clock, 3.3 miles closure. tail on, 
sb 3 o'clock, 37.9 miles closure. and 28366.4 feet below
sb 4 o'clock, 43.7 miles closure. and 28366.4 feet below
sb 3 o'clock, 46.9 miles closure. and 28366.4 feet below
sb 4 o'clock, 50.8 miles closure. and 28366.4 feet below
sb 3 o'clock, 51.7 miles closure. and 28366.4 feet below
sb 3 o'clock, 56.3 miles closure. and 28366.4 feet below
above.wav&i.wav

**Comment by munawarb** [comment]
Hi @burakyuksek,
These are the programmatic names of the objects. I'll need to make screen-reader friendly names for them. Thanks for reporting the issue.
