### ISSUE TITLE
The new way of loading audio produces clicks

### ISSUE THREAD

**Issue by burakyuksek** [munawarb/Three-D-Velocity#92]
Hello,
This especially occurs when loading the menu and in-game cut scenes when starting a game.

**Comment by munawarb** [comment]
Hi @burakyuksek,
Can you post the version of your BPCSharedComponent.dll file? I'm not able to reproduce this problem.

**Comment by munawarb** [comment]
I'm not able to reproduce this.

**Comment by munawarb** [comment]
Related to #102 .
