### ISSUE TITLE
Pitch does not change much

### ISSUE THREAD

**Issue by burakyuksek** [munawarb/Three-D-Velocity#99]
Hello,
The pitch range of the aircraft sound seems to be lower. Also it doesn't change much when opening afterburners, thus the aircraft feels slower.

**Comment by munawarb** [comment]
Hi,
Thanks for this feedback. It's using XAudio2 now which has completely different ways of controlling pitch. Which sound is not increasing like it used to? It's going to be an ongoing effort to adapt to the new library so feedback like this is helpful.

**Comment by burakyuksek** [comment]
The whole pitch range seems to have changed. You should look at all sounds that change pitch just in case. The aircraft engine and lock tone are 2 examples I can give.

**Comment by munawarb** [comment]
I worked a lot on the throttle pitch. Is it the rumble of the air intake that's off?  The throttle itself sounds fine and so does the targeting tone.

**Comment by burakyuksek** [comment]
The engine is the one that's wrong. Also it doesn't change pitch at all in afterburners.

Munawar Bijani <notifications@github.com> şunları yazdı (1 Eyl 2019 20:17):

> I worked a lot on the throttle pitch. Is it the rumble of the air intake that's off? The throttle itself sounds fine and so does the targeting tone.
>

**Comment by munawarb** [comment]
I see the problem here. The engine frequency is using the throttle position instead of the engine speed like it's supposed to. So once you put the throttle to full forward, the frequency will no longer increase. Thanks for reporting it!
